### ISSUE TITLE
Add option to change sounds volume

### ISSUE THREAD

**Issue by tomekbielaszewski** [BartoszCoyote/GoPomodoro#13]
Add option to chnage sounds volume:
`gopom start my_task --master-volume`
`gopom start my_task --work-volume`
`gopom start my_task --finish-volume`

or mute them completely:
`gopom start my_task --mute-all`
`gopom start my_task --mute-work`
`gopom start my_task --mute-finish`

**Comment by michal-franc** [comment]
This could be linked to another request to set volume up or down.

**Comment by tomekbielaszewski** [comment]
I don't see one :D also - those settings could be present in config file as well

**Comment by tomekbielaszewski** [comment]
Chenged the description to include volume changing

**Comment by tomekbielaszewski** [comment]
done in #20
