### ISSUE TITLE
Break work session and treat it as not finished session

### ISSUE THREAD

**Issue by michal-franc** [BartoszCoyote/GoPomodoro#24]
When you get distracted you should end pomodoro and start a new one to work in focus.

During work session when you click enter on terminal with gopomodoro - the work session should end and be treated as `interrupted session` (this would be later counted as partial pomodoro)

**Comment by tomekbielaszewski** [comment]
This function is quite handy! 
I tried to use it and I tested the experimental version on PR and currently only `Enter` interrupts the Pomodoro session by restarting the count down. The log `Pomodoro was interrupted.` is vague, but hey! WIP!
Progressbar is getting multiplicated which does not look good. Maybe there is a way to listen to keystrokes without printing the input 🤔
I really like the hack with bool pointer :D This is a thing you couldn't do in Java for instance
